### ISSUE TITLE
Map /app folder as a volume for local development

### ISSUE THREAD

**Issue by brandontamm** [hoangstark/docker-bedrock#1]
I haven't been able to figure out or find a good google resource to figure out how this type of command works with Docker-compose's version '2' ...

Example:
`
volumes:
     - ./app:/var/html/web/uploads
`

**Comment by h5tark** [comment]
@brandontamm You should do this:
`
volumes:
    - ./app:/usr/share/nginx/html/web/app
`

**Comment by brandontamm** [comment]
Sorry, I suppose that would help. 

I am on mac OSX and use homebrew for dependencies: 
- docker
- docker-compose
- docker-machine
- docker-machine-nfs

Couldn't figure out how to map the volume so I can develop locally.

Also wasn't sure I saw in the source where the download scripting was for bedrock?

**Comment by h5tark** [comment]
@brandontamm  Sorry, I didn't finish the document yet.

My docker-compose file was created to work with existing bedrock projects. To start using docker, you should create bedrock project with your local terminal first:
`composer create-project roots/bedrock`

Then place [docker-compose.yml](https://github.com/hoangstark/docker-bedrock/raw/master/docker-compose.yml) inside your project directory.

Then run 
`docker-compose up -d`

Docker will automatically map your project directory.

**Comment by brandontamm** [comment]
Thank you for the additional instructions - it's a great project..clean & minimal :)

**Comment by h5tark** [comment]
@brandontamm You are welcome. In addition, the mysql db directory is placed in `./web/app/uploads/docker-mysqldb`, that already ignored by git, so Docker for Bedrock will work well with git and any existing bedrock project.

**Comment by brandontamm** [comment]
Is it possible to adapt the docker-compose and folder structure to spin up multiple wordpress sites? I dont suppose you could throw a couple more pointers out as to how that would work? :)

**Comment by brandontamm** [comment]
So I should be able to just drop in the previous mysql db (same structure) and use the same env variables?

Extra kudos if you convert the PHP image to alpine and include WP-CLI :)

**Comment by h5tark** [comment]
@brandontamm If you want to spin up another wordpress sites, you could use this `docker-compose.yml` file.

```version: '2'
services:
  nginx:
    image: hoangstark/bedrock-nginx:latest
    ports:
     - "81:80"
    volumes:
     - .:/usr/share/nginx/html
    networks:
     - wpnet
  php:
    image: hoangstark/bedrock-php:latest
    volumes:
     - .:/usr/share/nginx/html
    networks:
     - wpnet
  mysql:
    image: mysql:5.7
    ports:
     - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
    volumes:
     - ./web/app/uploads/docker-mysqldb:/var/lib/mysql
    networks:
     - wpnet
networks:
  wpnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
```

What I've changed are the exposed ports. The second wordpress will spin up with `nginx` at port `81` and `mysql` at port `3307`

So you have the first wordress site at `http://localhost` and the second site at `http://localhost:81`.

Do the same thing with another site.

This is the database configuration in .env file:
```
DB_NAME=wordpress
DB_USER=wordpress
DB_PASSWORD=secret
DB_HOST=mysql
```
